/* Generated By:JavaCC: Do not edit this line. TokenManager.java Version 5.0 */
/* JavaCCOptions:SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.happypeople.hsh.hsh.parsers;

/**
 * An implementation for this interface is generated by
 * JavaCCParser.  The user is free to use any implementation
 * of their choice.
 */

public interface TokenManager {

  /** This gets the next token from the input stream.
   *  A token of kind 0 (<EOF>) should be returned on EOF.
   */
  public Token getNextToken();

}
/* JavaCC - OriginalChecksum=f25bba1b4906c73671362bd8974befbd (do not edit this line) */
